src/main/java/edu/iu/dlib/amppd/repository/UnitRepository.java, src/test/java/edu/iu/dlib/amppd/repository/UnitRepositoryTests.java
Unit tests have same issue with permission and need to be fixed later.
=> AMP-106: add repository and tests for Unit

pom.xml, src/main/java/edu/iu/dlib/amppd/model/AmpData.java, src/main/java/edu/iu/dlib/amppd/model/Asset.java, src/main/java/edu/iu/dlib/amppd/model/Content.java, src/main/java/edu/iu/dlib/amppd/model/MgmModeIo.java, src/main/java/edu/iu/dlib/amppd/model/Supplement.java, src/main/java/edu/iu/dlib/amppd/security/SecurityConfig.java, src/main/resources/application.properties, src/test/java/edu/iu/dlib/amppd/repository/CollectionRepositoryTests.java
This pull request includes indentation, MappedSuperclass annotation changes and csrf bypassing changes
=> Amp 132 pass tests

src/main/java/edu/indiana/dlib/amppd/config/ConfigProperties.java, src/main/java/edu/indiana/dlib/amppd/service/impl/FileStorageServiceImpl.java
Adding configuration details for AMP property
=> Amp 162 property

src/main/java/edu/indiana/dlib/amppd/service/impl/FileStorageServiceImpl.java, src/main/resources/application.properties
Fixing the Autowired annotations
=> AMP-162_fixes

src/test/java/edu/indiana/dlib/amppd/controller/JobControllerTests.java, src/test/java/edu/indiana/dlib/amppd/service/GalaxyDataServiceTests.java, src/test/java/edu/indiana/dlib/amppd/service/JobServiceTests.java, src/test/java/edu/indiana/dlib/amppd/service/WorkflowServiceTests.java
=> AMP-273: ignore some failing tests due to media file used by tests not

src/test/java/edu/indiana/dlib/amppd/controller/WorkflowControllerTests.java, src/test/java/edu/indiana/dlib/amppd/service/WorkflowServiceTests.java
=> AMP-418 fix workflow service/controller test with test helper to preload

src/main/java/edu/indiana/dlib/amppd/repository/DataentityRepository.java, src/main/java/edu/indiana/dlib/amppd/repository/ItemRepository.java, src/test/java/edu/indiana/dlib/amppd/repository/ItemRepositoryTests.java, src/test/java/edu/indiana/dlib/amppd/testData/ModelTemplates.java
=> AMP-443: add logic and tests for search item by name/description

src/test/java/edu/indiana/dlib/amppd/controller/FileUploadControllerTests.java, src/test/java/edu/indiana/dlib/amppd/controller/JobControllerTests.java, src/test/java/edu/indiana/dlib/amppd/service/BatchServiceTests.java, src/test/java/edu/indiana/dlib/amppd/service/GalaxyDataServiceTests.java, src/test/java/edu/indiana/dlib/amppd/service/JobServiceTests.java, src/test/java/edu/indiana/dlib/amppd/service/PreprocessServiceTests.java
=> AMP-553: add ignore/comments to tests that cant run on Bamboo due to

src/main/java/edu/indiana/dlib/amppd/service/impl/AmpUserServiceImpl.java, src/main/resources/application.properties, src/test/java/edu/indiana/dlib/amppd/service/AmpUserServiceTests.java
This PR involves a new entry to the property file
=> Amp 499 fix tests

src/main/java/edu/indiana/dlib/amppd/controller/AmpUserController.java, src/main/java/edu/indiana/dlib/amppd/model/AmpUser.java, src/main/java/edu/indiana/dlib/amppd/model/Passwordresettoken.java, src/main/java/edu/indiana/dlib/amppd/repository/PasswordTokenRepository.java, src/main/java/edu/indiana/dlib/amppd/service/AmpUserService.java, src/main/java/edu/indiana/dlib/amppd/service/impl/AmpUserServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/web/AuthResponse.java, src/test/java/edu/indiana/dlib/amppd/service/AmpUserServiceTests.java
Added a function to fetch email id and prepopulate it on the reset password page. Also added logging to some files
=> AMP-585_loggingAndEmail

src/main/java/edu/indiana/dlib/amppd/service/FileStorageService.java, src/main/java/edu/indiana/dlib/amppd/service/impl/BatchServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/service/impl/BatchValidationServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/service/impl/FileStorageServiceImpl.java, src/test/java/edu/indiana/dlib/amppd/service/BatchServiceTests.java, src/test/java/edu/indiana/dlib/amppd/service/FileStorageServiceTests.java
Exposes a method in FileStorageService to encode values using %(char hex).   Adds methods to FileStorageService to get the drop box path for the unit and collection using the new encoding.  Updates BatchValidationService and BatchService to use the new methods.
=> Amp 598 sanitizing directory paths

src/main/java/edu/indiana/dlib/amppd/controller/BatchController.java, src/main/java/edu/indiana/dlib/amppd/model/Passwordresettoken.java, src/main/java/edu/indiana/dlib/amppd/model/Primaryfile.java, src/main/java/edu/indiana/dlib/amppd/repository/PrimaryfileRepository.java, src/main/java/edu/indiana/dlib/amppd/service/BatchService.java, src/main/java/edu/indiana/dlib/amppd/service/impl/BatchServiceImpl.java, src/test/java/edu/indiana/dlib/amppd/service/BatchServiceTests.java, src/test/resources/batch_manifest_for_testing_duplication.csv
This fixes all cases for duplication of the primary file/supplement file and lists the errors for each row at the end of processing.
=> Amp 587 part ii

src/main/java/edu/indiana/dlib/amppd/repository/ItemRepository.java, src/main/java/edu/indiana/dlib/amppd/repository/PrimaryfileRepository.java, src/test/java/edu/indiana/dlib/amppd/repository/ItemRepositoryTests.java, src/test/java/edu/indiana/dlib/amppd/repository/PrimaryfileRepositoryTests.java
Updating Primaryfile and Item repositories to have case insensitive search
=> Amp 640 case insensitive search

src/main/java/edu/indiana/dlib/amppd/service/impl/AmpUserServiceImpl.java
A small change for handling an exception I came across while working on AMP-655
=> AMP-655_exceptionHandling

src/main/resources/application.properties
Updating application properties to increase file upload size
=> Amp 334 upload size

src/main/java/edu/indiana/dlib/amppd/model/Dataentity.java, src/main/java/edu/indiana/dlib/amppd/repository/DataentityRepository.java, src/main/java/edu/indiana/dlib/amppd/repository/ItemRepository.java, src/main/java/edu/indiana/dlib/amppd/repository/PrimaryfileRepository.java, src/main/java/edu/indiana/dlib/amppd/service/impl/BatchServiceImpl.java, src/test/java/edu/indiana/dlib/amppd/repository/ItemRepositoryTests.java, src/test/java/edu/indiana/dlib/amppd/repository/PrimaryfileRepositoryTests.java, src/test/java/edu/indiana/dlib/amppd/testData/ModelTemplates.java, src/test/java/edu/indiana/dlib/amppd/util/TestHelper.java
Changing dates to human readable timestamps.  Included is a script to execute BEFORE merging this PR.  There are a few dates that are not human readable in the database relating to spring sessions, but this should cover the majority of cases.  
[update_dates.txt](https://github.com/AudiovisualMetadataPlatform/amppd/files/4489854/update_dates.txt)
=> Amp 650 human readable dates

src/main/java/edu/indiana/dlib/amppd/service/impl/AmpUserServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/service/impl/BatchServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/service/impl/BatchValidationServiceImpl.java
The validation for external item ID (source ID previously) to be present has been removed. All batch tests pass as per the screenshot attached to the story.
=> Amp 678 source

src/test/java/edu/indiana/dlib/amppd/service/BatchServiceTests.java, src/test/resources/batch_manifest_for_testing_blank_ItemID.csv
Adding a test case for allowing blank external Item ID
=> AMP-678_addingTestCase

src/main/java/edu/indiana/dlib/amppd/controller/DashboardController.java, src/main/java/edu/indiana/dlib/amppd/repository/PrimaryfileRepository.java, src/main/java/edu/indiana/dlib/amppd/service/DashboardService.java, src/main/java/edu/indiana/dlib/amppd/service/impl/DashboardServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/web/DashboardResult.java, src/main/java/edu/indiana/dlib/amppd/web/GalaxyJobState.java, src/test/java/edu/indiana/dlib/amppd/service/DashboardServiceTests.java
Initial implementation of the workflow dashboard.  Adds a new controller and service to handle dashboard requests.  Currently, the only piece of data we are missing is the workflow name.  I will update the PR when that becomes accessible. For the time being it is using workflowId
=> Adding amppd support for the workflow dashboard

src/main/java/edu/indiana/dlib/amppd/config/SecurityConfig.java, src/main/java/edu/indiana/dlib/amppd/controller/AmpUserController.java, src/main/java/edu/indiana/dlib/amppd/model/AmpUser.java, src/main/java/edu/indiana/dlib/amppd/repository/AmpUserRepository.java, src/main/java/edu/indiana/dlib/amppd/service/impl/AmpUserServiceImpl.java, src/test/java/edu/indiana/dlib/amppd/controller/AmpUserControllerTests.java, src/test/java/edu/indiana/dlib/amppd/service/AmpUserServiceTests.java, src/test/java/edu/indiana/dlib/amppd/util/TestHelper.java
Changes the back end to use distinct username, email, first, and last names.  Also changes routes to match the front end.  Registration still only contains one field (email), which is used for both username and email.  Username is used from that point on for all authentication and email is used to email the user.
=> Refactoring login and auth fields

src/main/java/edu/indiana/dlib/amppd/config/SecurityConfig.java, src/main/java/edu/indiana/dlib/amppd/controller/DropboxController.java, src/main/java/edu/indiana/dlib/amppd/service/DropboxService.java, src/main/java/edu/indiana/dlib/amppd/service/FileStorageService.java, src/main/java/edu/indiana/dlib/amppd/service/impl/AmpUserServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/service/impl/BatchServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/service/impl/BatchValidationServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/service/impl/DropboxServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/service/impl/FileStorageServiceImpl.java, src/test/java/edu/indiana/dlib/amppd/controller/DropboxControllerTests.java, src/test/java/edu/indiana/dlib/amppd/service/BatchServiceTests.java, src/test/java/edu/indiana/dlib/amppd/service/DropboxServiceTests.java, src/test/java/edu/indiana/dlib/amppd/service/FileStorageServiceTests.java, src/test/java/edu/indiana/dlib/amppd/util/TestHelper.java
In addition to dropbox stuff, I added some improvement to the handling of current user when auth is turned off,:so if user did go through login, then the current user is still pulled from the session; otherwise the default user is used.
=> Amp 695 dropbox

src/main/java/edu/indiana/dlib/amppd/controller/DashboardController.java, src/main/java/edu/indiana/dlib/amppd/controller/MediaController.java, src/main/java/edu/indiana/dlib/amppd/model/DashboardResult.java, src/main/java/edu/indiana/dlib/amppd/repository/DashboardRepository.java, src/main/java/edu/indiana/dlib/amppd/service/DashboardService.java, src/main/java/edu/indiana/dlib/amppd/service/MediaService.java, src/main/java/edu/indiana/dlib/amppd/service/impl/DashboardServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/service/impl/JobServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/service/impl/MediaServiceImpl.java, src/test/java/edu/indiana/dlib/amppd/controller/MediaControllerTests.java, src/test/java/edu/indiana/dlib/amppd/service/DashboardServiceTests.java, src/test/java/edu/indiana/dlib/amppd/service/MediaServiceTests.java, src/test/java/edu/indiana/dlib/amppd/util/TestHelper.java
add a small unit test fix. since this can't run locally on windows, it can only be detected on bamboo
=> Amp 700 output

src/main/java/edu/indiana/dlib/amppd/model/DashboardResult.java, src/main/java/edu/indiana/dlib/amppd/repository/PrimaryfileRepository.java, src/main/java/edu/indiana/dlib/amppd/service/impl/DashboardServiceImpl.java
Need to do this merge to sync with amppd-ui staging merge for AMP-803 as ewll
* AMP-782: add primaryfileId for linking media file
* AMP-782: remove test code
=> Amp 782 source link (#153)

src/main/java/edu/indiana/dlib/amppd/model/Content.java, src/main/java/edu/indiana/dlib/amppd/service/impl/BatchServiceImpl.java, src/test/java/edu/indiana/dlib/amppd/service/BatchServiceTests.java
Adding external source to batch processing
=> Amp 731 change external

src/main/java/edu/indiana/dlib/amppd/repository/DashboardRepositoryCustomImpl.java
Starting pagination at 0 rather than 1
=> Fixing dashboard result bug

src/main/java/edu/indiana/dlib/amppd/controller/DashboardController.java, src/main/java/edu/indiana/dlib/amppd/repository/DashboardRepositoryCustomImpl.java, src/main/java/edu/indiana/dlib/amppd/service/DashboardService.java, src/main/java/edu/indiana/dlib/amppd/service/impl/DashboardServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/web/DashboardSearchQuery.java
Adding support for marking items as final, and also allows users to be able to filter results by items selected as final.
=> AMP-838 Adding support for isFinal in deliverables ui

src/main/java/edu/indiana/dlib/amppd/config/SecurityConfig.java, src/main/java/edu/indiana/dlib/amppd/model/BagContent.java, src/main/java/edu/indiana/dlib/amppd/model/DashboardResult.java, src/main/java/edu/indiana/dlib/amppd/repository/DashboardRepositoryCustomImpl.java, src/main/java/edu/indiana/dlib/amppd/service/DashboardService.java, src/main/java/edu/indiana/dlib/amppd/service/impl/BagServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/service/impl/DashboardServiceImpl.java, src/main/resources/application.properties, src/test/java/edu/indiana/dlib/amppd/service/DashboardServiceTests.java
- add/rename date created/updated fields to workflow result
- update logic in bag and dashboard service to populate new date fields
=> Amp 897 job time

src/main/java/edu/indiana/dlib/amppd/controller/DashboardController.java, src/main/java/edu/indiana/dlib/amppd/model/DashboardResult.java, src/main/java/edu/indiana/dlib/amppd/repository/DashboardRepository.java, src/main/java/edu/indiana/dlib/amppd/repository/PrimaryfileRepository.java, src/main/java/edu/indiana/dlib/amppd/service/DashboardService.java, src/main/java/edu/indiana/dlib/amppd/service/WorkflowService.java, src/main/java/edu/indiana/dlib/amppd/service/impl/DashboardServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/service/impl/JobServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/service/impl/WorkflowServiceImpl.java, src/main/resources/application.properties, src/test/java/edu/indiana/dlib/amppd/service/BagServiceTests.java, src/test/java/edu/indiana/dlib/amppd/service/DashboardServiceTests.java, src/test/java/edu/indiana/dlib/amppd/service/WorkflowServiceTests.java, src/test/java/edu/indiana/dlib/amppd/util/TestHelper.java
See:
https://bugs.dlib.indiana.edu/browse/AMP-931?focusedCommentId=3990109&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-3990109
https://bugs.dlib.indiana.edu/browse/AMP-931?focusedCommentId=3990110&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-3990110
=> Amp 931 refresh results

src/main/java/edu/indiana/dlib/amppd/service/impl/DashboardServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/service/impl/MediaServiceImpl.java
- small fix to use last job of a step for workflow step label and tool
info
- handle deprecated galaxy data type segments
=> AMP-893: small fixes in preparation for staging update

src/main/java/edu/indiana/dlib/amppd/service/PreprocessService.java, src/main/java/edu/indiana/dlib/amppd/service/impl/BatchServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/service/impl/PreprocessServiceImpl.java
Updates logic for supplements as well as moves media info json after file has moved.
=> Moving json after we move files.

src/main/java/edu/indiana/dlib/amppd/controller/JobController.java, src/main/java/edu/indiana/dlib/amppd/service/JobService.java, src/main/java/edu/indiana/dlib/amppd/service/impl/JobServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/web/WorkflowOutputResult.java, src/test/java/edu/indiana/dlib/amppd/service/JobServiceTests.java, src/test/java/edu/indiana/dlib/amppd/service/WorkflowResultServiceTests.java, src/test/java/edu/indiana/dlib/amppd/util/TestHelper.java
Changes the return type for workflow submissions to include detailed information for each file submitted.
=> Amp 891 wf submit error details

src/main/java/edu/indiana/dlib/amppd/controller/JobController.java, src/main/java/edu/indiana/dlib/amppd/service/JobService.java, src/main/java/edu/indiana/dlib/amppd/service/impl/JobServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/web/WorkflowOutputResult.java, src/main/resources/application.properties, src/test/java/edu/indiana/dlib/amppd/service/JobServiceTests.java, src/test/java/edu/indiana/dlib/amppd/service/WorkflowResultServiceTests.java, src/test/java/edu/indiana/dlib/amppd/util/TestHelper.java
API endpoints to start with /rest
=> Amp 954 rest endpoint change

src/main/java/edu/indiana/dlib/amppd/config/JwtRequestFilter.java, src/main/java/edu/indiana/dlib/amppd/service/impl/JobServiceImpl.java, src/main/resources/application.properties, src/main/resources/logback-spring.xml
JwtRequestFilter.doFilterInternal: 
- log warning when auth fails due to various reasons
-  log debug when auth succeeds
The purpose is to log important info but not flood the logs with too many messages. so if some message tend to repeat too often, we should consider lowering the level. Currently, tst is at DEBUG level, staging is at INFO level. dev is TRACE by default.
=> Amp 1010 log level

src/main/java/edu/indiana/dlib/amppd/service/impl/WorkflowResultServiceImpl.java
=> AMP-960: fix a bug in workflow result table refresh related in dataset

src/main/java/edu/indiana/dlib/amppd/service/impl/WorkflowResultServiceImpl.java
=> Amp 1014 dashboard export

src/main/java/edu/indiana/dlib/amppd/repository/WorkflowResultRepositoryCustomImpl.java, src/main/java/edu/indiana/dlib/amppd/web/WorkflowResultFilterValues.java, src/main/java/edu/indiana/dlib/amppd/web/WorkflowResultSearchQuery.java
Adds lists for new collection filter in the workflow dashboard
=> Adding collection filter

src/main/java/edu/indiana/dlib/amppd/repository/WorkflowResultRepositoryCustomImpl.java, src/main/java/edu/indiana/dlib/amppd/web/WorkflowResultFilterValues.java, src/main/java/edu/indiana/dlib/amppd/web/WorkflowResultSearchQuery.java
Adding External Id Filter  and Output Filter To Dash Board
=> AMP-1084_Dashboard_outputFilter_externalIdFilter

src/main/java/edu/indiana/dlib/amppd/service/impl/JobServiceImpl.java
Adding context population to applause detection tool params
=> Amp 1171 applause xml

src/main/java/edu/indiana/dlib/amppd/service/impl/MediaServiceImpl.java
=> AMP-1814: do not use JSONException which might be removed in newer

amp_build.py
=> import amp_build script

src/main/java/edu/indiana/dlib/amppd/repository/SupplementRepository.java
- open up SupplementRepository Rest API to allow list all supplements at
once
=> AMP-1379: 

src/main/java/edu/indiana/dlib/amppd/service/impl/MgmRefreshServiceImpl.java
=> AMP-2047: tmp work-around on issue of incorrect section ID generated by

src/main/java/edu/indiana/dlib/amppd/controller/DataentityController.java, src/main/java/edu/indiana/dlib/amppd/controller/FileUploadController.java, src/main/java/edu/indiana/dlib/amppd/model/ItemSupplement.java, src/main/java/edu/indiana/dlib/amppd/model/PrimaryfileSupplement.java, src/main/java/edu/indiana/dlib/amppd/model/Unit.java, src/main/java/edu/indiana/dlib/amppd/model/UnitSupplement.java, src/main/java/edu/indiana/dlib/amppd/model/projection/UnitDetail.java, src/main/java/edu/indiana/dlib/amppd/model/projection/UnitSupplementBrief.java, src/main/java/edu/indiana/dlib/amppd/model/projection/UnitSupplementDetail.java, src/main/java/edu/indiana/dlib/amppd/repository/UnitSupplementRepository.java, src/main/java/edu/indiana/dlib/amppd/service/impl/DataentityServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/service/impl/FileStorageServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/service/impl/MediaServiceImpl.java, src/test/java/edu/indiana/dlib/amppd/controller/FileUploadControllerTests.java, src/test/java/edu/indiana/dlib/amppd/fixture/DataEntityTemplate.java, src/test/java/edu/indiana/dlib/amppd/fixture/DataentityProcessor.java, src/test/java/edu/indiana/dlib/amppd/repository/UnitSupplementRepositoryTests.java, src/test/java/edu/indiana/dlib/amppd/service/FileStorageServiceTests.java, src/test/java/edu/indiana/dlib/amppd/util/TestHelper.java, src/test/java/edu/indiana/dlib/amppd/util/TestUtil.java
data model entity and table
repository
validation
projection
CRUD endpoints
services: data entity, file upload, media, bag, deliverable, job etc
controllers: data entity, file upload, media, bag, deliverable, job etc
Unit tests
=> AMP-2021: add/update all classes for UnitSupplement

pom.xml
=> AMP-1819 bamboo tests

src/main/java/edu/indiana/dlib/amppd/controller/WorkflowController.java, src/main/java/edu/indiana/dlib/amppd/service/WorkflowService.java, src/main/java/edu/indiana/dlib/amppd/service/impl/WorkflowServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/web/WorkflowFilterValues.java, src/main/java/edu/indiana/dlib/amppd/web/WorkflowResponse.java, src/test/java/edu/indiana/dlib/amppd/service/WorkflowServiceTests.java
Updated `WorkflowController` listing method `listWorkflows` to add filtering params
```
@RequestParam(required = false) String[] tag,
@RequestParam(required = false) String[] name,
@RequestParam(required = false) String[] annotation,
@RequestParam(required = false) String[] creator,
@RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) Date[] dateRange)
```
I kept this `@GetMapping` as it is and added new params if you suggest I can make it `@PostMapping` and instead of adding new params I will create a new class for `searchRequestParams`.
`WorkflowSevice` updated and all filters are added. First, we loop on workflows for each param separately then I took intersection of all List so I can have unique workflows after search.
**Request URL:** …
=> [Feature, AMP-1856] Search workflows - backend

src/main/java/edu/indiana/dlib/amppd/service/impl/WorkflowServiceImpl.java
=> AMP-2256: handle workflow input format either as a String or an array of

src/main/java/edu/indiana/dlib/amppd/controller/WorkflowResultController.java, src/main/java/edu/indiana/dlib/amppd/repository/WorkflowResultRepository.java
that don't exist in workflow result table
=> AMP-2256: fix issue with previous query when outputTypes contain some

src/main/java/edu/indiana/dlib/amppd/AmppdStartupRunner.java, src/main/java/edu/indiana/dlib/amppd/controller/PermissionController.java, src/main/java/edu/indiana/dlib/amppd/model/AmpObject.java, src/main/java/edu/indiana/dlib/amppd/model/AmpUser.java, src/main/java/edu/indiana/dlib/amppd/model/Unit.java, src/main/java/edu/indiana/dlib/amppd/model/ac/Action.java, src/main/java/edu/indiana/dlib/amppd/model/ac/Role.java, src/main/java/edu/indiana/dlib/amppd/model/ac/RoleAction.java, src/main/java/edu/indiana/dlib/amppd/model/ac/RoleAssignment.java, src/main/java/edu/indiana/dlib/amppd/repository/ActionRepository.java, src/main/java/edu/indiana/dlib/amppd/repository/AmpUserRepository.java, src/main/java/edu/indiana/dlib/amppd/repository/RoleAssignmentRepository.java, src/main/java/edu/indiana/dlib/amppd/repository/RoleRepository.java, src/main/java/edu/indiana/dlib/amppd/repository/UnitRepository.java, src/main/java/edu/indiana/dlib/amppd/service/MgmRefreshService.java, src/main/java/edu/indiana/dlib/amppd/service/PermissionRefreshService.java, src/main/java/edu/indiana/dlib/amppd/service/PermissionService.java, src/main/java/edu/indiana/dlib/amppd/service/impl/MgmRefreshServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/service/impl/PermissionRefreshServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/service/impl/PermissionServiceImpl.java, src/main/resources/db/ac_action.csv, src/main/resources/db/ac_role.csv, src/main/resources/db/ac_role_action.csv
- add permission spreadsheets
- impl init permission tables
- impl hasPermission (POC)
- some refactor on AC models
- some refactor/extension on related classes
=> AMP-2361/2363

src/main/resources/application.properties
Fixed
Named Entity Recognition > "Precision/Recall of All Entity Instances (mapped)" and "Precision/Recall of Unique Entities (mapped)" > Ground truth entities(Common) --> try to upload a groundtruth file (Category: Groundtruth-ner_all_common) ===> Error: category must be one of the enumerated values defined in configuration property
=> Feature/amp 2194/test results

src/main/java/edu/indiana/dlib/amppd/controller/MgmEvaluationController.java, src/main/java/edu/indiana/dlib/amppd/repository/MgmEvaluationTestRepository.java, src/main/java/edu/indiana/dlib/amppd/repository/MgmEvaluationTestRepositoryCustom.java, src/main/java/edu/indiana/dlib/amppd/repository/MgmEvaluationTestRepositoryCustomImpl.java, src/main/java/edu/indiana/dlib/amppd/service/MgmEvaluationService.java, src/main/java/edu/indiana/dlib/amppd/service/impl/MgmEvaluationServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/web/MgmEvaluationSearchQuery.java, src/main/java/edu/indiana/dlib/amppd/web/MgmEvaluationTestResponse.java
**POST: /rest/mgm-evaluation-test/query** 
**Request Body:**
```
{
"sortRule":{"columnName":"id","orderByDescending":true},
"pageNum":1,
"resultsPerPage":10,
"filterByCategories":[],
"filterByMstTools":[]
}
```
=> [Feature, AMP-2194] API endpoint for displaying test results

src/main/java/edu/indiana/dlib/amppd/service/impl/MediaServiceImpl.java
Removed extra conditions from api call
=> [Bug, AMP-2187] Deliverable page is stuck when returning results

src/main/java/edu/indiana/dlib/amppd/repository/MgmEvaluationTestRepositoryCustomImpl.java, src/main/java/edu/indiana/dlib/amppd/web/MgmEvaluationSearchQuery.java, src/main/java/edu/indiana/dlib/amppd/web/MgmEvaluationTestFilters.java
New filter added for MGM Evaluation Test Status to get only success rows from db
=> [Feature, AMP-2427] Add filters to API for display test results page

src/main/java/edu/indiana/dlib/amppd/controller/WorkflowResultController.java, src/main/java/edu/indiana/dlib/amppd/model/Asset.java, src/main/java/edu/indiana/dlib/amppd/repository/WorkflowResultRepository.java, src/main/java/edu/indiana/dlib/amppd/service/MediaService.java, src/main/java/edu/indiana/dlib/amppd/service/impl/JobServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/service/impl/MediaServiceImpl.java, src/main/resources/db/ac_action.csv
=> AMP-2466 all changes for extending submit partial workflow with matching

src/main/java/edu/indiana/dlib/amppd/model/dto/ActionDto.java, src/main/java/edu/indiana/dlib/amppd/model/dto/AmpUserDto.java, src/main/java/edu/indiana/dlib/amppd/model/dto/RoleAction.java, src/main/java/edu/indiana/dlib/amppd/model/dto/RoleActionsDto.java, src/main/java/edu/indiana/dlib/amppd/model/dto/RoleActionsId.java, src/main/java/edu/indiana/dlib/amppd/model/dto/RoleAssignmentDto.java, src/main/java/edu/indiana/dlib/amppd/model/dto/RoleDto.java, src/main/java/edu/indiana/dlib/amppd/repository/RoleRepository.java, src/main/java/edu/indiana/dlib/amppd/service/PermissionRefreshService.java, src/main/java/edu/indiana/dlib/amppd/service/impl/PermissionRefreshServiceImpl.java
- add more DTOs
- fix issues in AC table refreshing due to new Role/Action APIs
=> AMP-2591_2607:

src/main/java/edu/indiana/dlib/amppd/service/impl/MediaServiceImpl.java
Reverts AudiovisualMetadataPlatform/amppd#528
=> Revert "AMP-2633: use host relative URL"

amp_hook_config.py, src/main/java/edu/indiana/dlib/amppd/controller/AmpUserController.java, src/main/java/edu/indiana/dlib/amppd/service/impl/AmpUserServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/web/AuthResponse.java
- fix https config
- refactor AmpUser registration and account action
=> AMP-2852/2853:

src/main/java/edu/indiana/dlib/amppd/config/SecurityConfig.java, src/main/java/edu/indiana/dlib/amppd/controller/MediaController.java
- enable auth on media links
- revert media API to return redirect instead of symlink url
=> AMP-2990/3006:

src/main/java/edu/indiana/dlib/amppd/controller/MediaController.java
- change link API again to return symlink instead of redirect, so things in UI can be worked out easier
=> AMP-3006/2990:

pom.xml, src/main/java/edu/indiana/dlib/amppd/config/SecurityConfig.java, src/main/java/edu/indiana/dlib/amppd/model/projection/CollectionBrief.java, src/main/java/edu/indiana/dlib/amppd/model/projection/CollectionDetail.java, src/main/java/edu/indiana/dlib/amppd/model/projection/CollectionSupplementBrief.java, src/main/java/edu/indiana/dlib/amppd/model/projection/CollectionSupplementDetail.java, src/main/java/edu/indiana/dlib/amppd/model/projection/ItemBrief.java, src/main/java/edu/indiana/dlib/amppd/model/projection/ItemDetail.java, src/main/java/edu/indiana/dlib/amppd/model/projection/ItemSupplementBrief.java, src/main/java/edu/indiana/dlib/amppd/model/projection/ItemSupplementDetail.java, src/main/java/edu/indiana/dlib/amppd/model/projection/MgmEvaluationTestBrief.java, src/main/java/edu/indiana/dlib/amppd/model/projection/MgmEvaluationTestDetail.java, src/main/java/edu/indiana/dlib/amppd/model/projection/MgmMetaDetail.java, src/main/java/edu/indiana/dlib/amppd/model/projection/MgmScoringParameterBrief.java, src/main/java/edu/indiana/dlib/amppd/model/projection/MgmScoringParameterDetail.java, src/main/java/edu/indiana/dlib/amppd/model/projection/MgmScoringToolDetail.java, src/main/java/edu/indiana/dlib/amppd/model/projection/PrimaryfileBrief.java, src/main/java/edu/indiana/dlib/amppd/model/projection/PrimaryfileDetail.java, src/main/java/edu/indiana/dlib/amppd/model/projection/PrimaryfileSupplementBrief.java, src/main/java/edu/indiana/dlib/amppd/model/projection/PrimaryfileSupplementDetail.java, src/main/java/edu/indiana/dlib/amppd/model/projection/UnitSupplementBrief.java, src/main/java/edu/indiana/dlib/amppd/model/projection/UnitSupplementDetail.java, src/main/java/edu/indiana/dlib/amppd/service/impl/MediaServiceImpl.java
- tag 1.0.2
- move parent IDs from brief to detail projections
=> AMP-2826/3096:

src/main/java/edu/indiana/dlib/amppd/handler/CollectionHandler.java, src/main/java/edu/indiana/dlib/amppd/handler/ItemHandler.java, src/main/java/edu/indiana/dlib/amppd/handler/PrimaryfileHandler.java, src/main/java/edu/indiana/dlib/amppd/handler/SupplementHandler.java, src/main/java/edu/indiana/dlib/amppd/handler/UnitHandler.java, src/main/java/edu/indiana/dlib/amppd/model/Bundle.java, src/main/java/edu/indiana/dlib/amppd/model/Collection.java, src/main/java/edu/indiana/dlib/amppd/model/CollectionSupplement.java, src/main/java/edu/indiana/dlib/amppd/model/Dataentity.java, src/main/java/edu/indiana/dlib/amppd/model/Item.java, src/main/java/edu/indiana/dlib/amppd/model/ItemSupplement.java, src/main/java/edu/indiana/dlib/amppd/model/Primaryfile.java, src/main/java/edu/indiana/dlib/amppd/model/PrimaryfileSupplement.java, src/main/java/edu/indiana/dlib/amppd/model/Unit.java, src/main/java/edu/indiana/dlib/amppd/model/UnitSupplement.java, src/main/java/edu/indiana/dlib/amppd/model/unused/HmgmTask.java, src/main/java/edu/indiana/dlib/amppd/model/unused/InputBag.java, src/main/java/edu/indiana/dlib/amppd/model/unused/Mgm.java, src/main/java/edu/indiana/dlib/amppd/model/unused/MgmMode.java, src/main/java/edu/indiana/dlib/amppd/model/unused/MgmModeInput.java, src/main/java/edu/indiana/dlib/amppd/model/unused/MgmModeIo.java, src/main/java/edu/indiana/dlib/amppd/model/unused/MgmModeOutput.java, src/main/java/edu/indiana/dlib/amppd/model/unused/UnitInfo.java, src/main/java/edu/indiana/dlib/amppd/model/unused/Workflow.java
- add error checking on deletable upon deletion
- remove PAUSED from incomplete status list
- add getDeletable to Dataentity
- return false on bundle deletable
=> AMP-3307/AMP-3489

src/main/java/edu/indiana/dlib/amppd/service/impl/FileStorageServiceImpl.java, src/main/java/edu/indiana/dlib/amppd/service/impl/MgmEvaluationServiceImpl.java
- add null checking on pathname for Eval test output and asset
=> AMP-3307/3533

src/main/java/edu/indiana/dlib/amppd/controller/WorkflowEditProxy.java, src/main/java/edu/indiana/dlib/amppd/security/JwtRequestFilter.java
- improve validRefUrl to be more strict
- replace header name with constant
=> AMP-3170/AMP-3705
